### ISSUE TITLE
Many performance issues

### ISSUE THREAD

**Issue by ntotten** [auth0/web-header#22]
![image](https://cloud.githubusercontent.com/assets/282782/20491016/d6ec7bdc-afc4-11e6-8e8d-b0ff19a093eb.png)

![image](https://cloud.githubusercontent.com/assets/282782/20491086/1a5a1b90-afc5-11e6-8200-eaf071f1bd58.png)

**Comment by ramasilveyra** [comment]
Fixed on the latest version https://github.com/auth0/web-header/pull/34 + the enhancement to the cdn-droid (mainly used to upload images for the blog) to compress the image before uploading them to the CDN.
